function htmlSnippet(title: string) {
  return `\`\`\`html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${title}</title>
  <style>
    body {
      margin: 0;
      min-height: 100vh;
      display: grid;
      place-items: center;
      font-family: Arial, sans-serif;
      background: #111827;
      color: white;
    }

    main {
      width: min(92vw, 720px);
      padding: 40px;
      border-radius: 22px;
      background: #172033;
      box-shadow: 0 24px 80px rgba(0, 0, 0, 0.32);
    }

    button {
      border: 0;
      border-radius: 12px;
      padding: 12px 18px;
      background: #38bdf8;
      color: #082f49;
      font-weight: 800;
      cursor: pointer;
    }
  </style>
</head>
<body>
  <main>
    <h1>${title}</h1>
    <p>This starter was generated by free local mode. For full multi-file edits, use the Coding Agent panel.</p>
    <button onclick="alert('Ready to build!')">Try it</button>
  </main>
</body>
</html>
\`\`\``;
}

export function getLocalAssistantReply(message: string) {
  const lower = message.toLowerCase();

  if (lower.includes("todo")) {
    return `Free local mode can build this as a multi-file project. Open Coding Agent, choose "Free local", and run: "create a todo app".\n\n${htmlSnippet("Todo App Starter")}`;
  }

  if (lower.includes("calculator")) {
    return `Free local mode can build a calculator. Open Coding Agent, choose "Free local", and run: "create a calculator".\n\n${htmlSnippet("Calculator Starter")}`;
  }

  if (
    lower.includes("landing") ||
    lower.includes("portfolio") ||
    lower.includes("website")
  ) {
    return `Free local mode can build this as index.html, style.css, and script.js. Open Coding Agent, choose "Free local", and run: "create a modern landing page".\n\n${htmlSnippet("Landing Page Starter")}`;
  }

  return `Free local mode is active because OPENAI_API_KEY is missing. For coding, use the Coding Agent panel and choose "Free local". It can generate landing pages, todo apps, calculators, and safe active-file updates without paid API calls.`;
}
